import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHandler} from '../functions/zasu-account/handler.mjs';
const origin='https://zasuworks.jp';
function setup(overrides={}){const calls=[];const deps={request:async x=>(calls.push(['request',x]),'11111111-1111-4111-8111-111111111111'),verify:async()=>({access_token:'access',refresh_token:'refresh',expires_at:123,user:{id:'user',email:'test@example.com'}}),authenticate:async()=>({id:'user',email:'test@example.com',sessionId:'session'}),profile:async()=>({display_name:'',locale:'ja',status:'active'}),update:async(_u,x)=>(calls.push(['update',x]),x),logout:async(_u,scope)=>calls.push(['logout',scope]),close:async()=>calls.push(['close']),limit:async()=>true,...overrides};return {handler:createHandler(deps),calls};}
function req(body,opts={}){return new Request('https://example.com/functions/v1/zasu-account',{method:opts.method||'POST',headers:{Origin:opts.origin||origin,'Content-Type':'application/json',...(opts.token?{Authorization:'Bearer token'}:{})},body:opts.method==='OPTIONS'?undefined:JSON.stringify(body)});}
test('foreign origin cannot trigger OTP',async()=>{const s=setup();assert.equal((await s.handler(req({action:'request',email:'test@example.com',purpose:'signup',consent:true},{origin:'https://evil.test'}))).status,403);assert.equal(s.calls.length,0)});
test('signup requires affirmative privacy consent',async()=>{const s=setup();assert.equal((await s.handler(req({action:'request',email:'test@example.com',purpose:'signup'}))).status,400);assert.equal(s.calls.length,0)});
test('request normalizes email and returns opaque challenge',async()=>{const s=setup();const r=await s.handler(req({action:'request',email:' Test@Example.COM ',purpose:'signup',consent:true}));assert.equal(r.status,200);assert.equal(s.calls[0][1].email,'test@example.com');assert.ok((await r.json()).challengeId);assert.equal(r.headers.get('Cache-Control'),'no-store')});
test('unknown login returns same accepted shape',async()=>{const s=setup({request:async()=>null});const r=await s.handler(req({action:'request',email:'missing@example.com',purpose:'login'}));assert.equal(r.status,200);assert.match((await r.json()).challengeId,/^[a-f0-9-]{36}$/)});
test('rate limit prevents mail issuance',async()=>{const s=setup({limit:async()=>false});assert.equal((await s.handler(req({action:'request',email:'test@example.com',purpose:'login'}))).status,429);assert.equal(s.calls.length,0)});
test('verification returns Supabase session',async()=>{const s=setup();const r=await s.handler(req({action:'verify',challengeId:'11111111-1111-4111-8111-111111111111',code:'123456'}));assert.equal(r.status,200);assert.equal((await r.json()).session.access_token,'access')});
test('expired or replayed code fails generically',async()=>{const s=setup({verify:async()=>null});const r=await s.handler(req({action:'verify',challengeId:'11111111-1111-4111-8111-111111111111',code:'123456'}));assert.equal(r.status,400);assert.equal((await r.json()).error,'invalid_code')});
test('profile requires bearer authentication',async()=>{const s=setup();assert.equal((await s.handler(req({action:'me'}))).status,401)});
test('revoked session cannot read profile',async()=>{const s=setup({authenticate:async()=>null});assert.equal((await s.handler(req({action:'me'},{token:true}))).status,401)});
test('profile is scoped to authenticated identity',async()=>{const s=setup();const r=await s.handler(req({action:'me',userId:'someone-else'},{token:true}));assert.equal(r.status,200);assert.equal((await r.json()).user.id,'user')});
test('profile updates reject server-owned fields',async()=>{const s=setup();assert.equal((await s.handler(req({action:'update',display_name:'Name',status:'active',user_id:'other'},{token:true}))).status,400);assert.equal(s.calls.length,0)});
test('valid display name and locale update uses verified identity',async()=>{const s=setup();assert.equal((await s.handler(req({action:'update',display_name:' 音楽家 ',locale:'en'},{token:true}))).status,200);assert.deepEqual(s.calls[0][1],{display_name:'音楽家',locale:'en'})});
test('logout all revokes all sessions',async()=>{const s=setup();assert.equal((await s.handler(req({action:'logout',scope:'global'},{token:true}))).status,200);assert.deepEqual(s.calls,[['logout','global']])});
test('account closure without fresh OTP proof is denied',async()=>{const s=setup();assert.equal((await s.handler(req({action:'close'},{token:true}))).status,400);assert.equal(s.calls.length,0)});
test('server errors never expose credentials or internals',async()=>{const s=setup({profile:async()=>{throw Error('service_role=secret')}});const r=await s.handler(req({action:'me'},{token:true}));assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/secret|service_role/)});
test('oversized and malformed request fail closed',async()=>{const s=setup();assert.equal((await s.handler(req({action:'request',email:'x'.repeat(5000)}))).status,413);assert.equal(s.calls.length,0)});
