import {test} from 'node:test';import assert from 'node:assert/strict';
let createCommerce;try{({createCommerce}=await import('../functions/zasu-account/commerce.mjs'))}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e}
const user={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',sessionId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',email:'account@example.test'};
const snapshot={orderId:'Order12345678901234567890',offer:{title:'ZASU VOCAL v1.0.0',version:'1.0.0'},products:['vocal'],amount:3980,currency:'JPY',status:'paid',buyerEmail:'purchase@example.test',payments:[{id:'Payment12345678901234567890',amount:3980,status:'COMPLETED'}],purchasedAt:'2026-10-01T00:00:00Z',verifiedAt:'2026-10-09T00:00:00Z'};
const order={id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',external_order_id:snapshot.orderId,owner_user_id:null,status:'paid',product_keys:['vocal'],title:snapshot.offer.title,purchased_version:'1.0.0',amount_minor:3980,currency:'JPY',purchased_at:snapshot.purchasedAt};
function setup({status='paid',email='purchase@example.test',owner=null,mailBudget=true,claimOwner=user.id,claimSession=user.sessionId}={}){
 let activeSession=true;const calls=[],rows={commerce_orders:[{...order,owner_user_id:owner}],purchase_claims:[]};let sent,code,signs=0;
 const db={rpc:async(n,a)=>{calls.push({name:n,args:a});if(n==='account_session_active')return {data:activeSession};if(n==='account_rate_check')return {data:mailBudget};if(n==='commerce_sync_order'){rows.commerce_orders[0].status=status;return {data:order.id}}if(n==='commerce_begin_claim'){rows.purchase_claims=[{id:a.p_id,order_id:order.id,user_id:claimOwner,session_id:claimSession,code_hash:a.p_hash,buyer_email_hash:a.p_email_hash,expires_at:new Date(Date.now()+600000).toISOString(),attempts:0}];return {data:!owner}}if(n==='commerce_finish_claim')return {data:true};if(n==='zasu_alert_delivery_config')return {data:{resend_api_key:'fixture',delivery:{domain_verified:true,transport_enabled:true,sending_domain:'example.test'}}};throw Error(n)},from(t){const conditions=[];let single=false;const q={select(){return q},eq(k,v){conditions.push(r=>r[k]===v);return q},order(){return q},limit(){return q},maybeSingle(){single=true;return q},single(){single=true;return q},then(fn){const a=(rows[t]||[]).filter(r=>conditions.every(f=>f(r)));fn({data:single?a[0]||null:a,error:null})}};return q},storage:{from(){return {createSignedUrl:async()=>{signs++;return {data:{signedUrl:'https://signed.example.test/file'}}}}}}};
 const deps={getVerifiedPurchase:async()=>({...snapshot,status,buyerEmail:email}),resolveOrder:async()=>snapshot.orderId,fetchMail:async(_url,opts)=>{sent=JSON.parse(opts.body);code=sent.text.match(/確認コード: (\d+)/)?.[1];return new Response('{}',{status:200})}};
 const service=()=>createCommerce({db,key:'fixture-key',...deps});
 return {revoke:()=>{activeSession=false},service,calls,rows,getSent:()=>sent,getCode:()=>code,signs:()=>signs,deps};
}
test('commerce implementation exists',()=>assert.equal(typeof createCommerce,'function'));
test('purchase email gets claim code, account email is never substituted',async()=>{const s=setup();const r=await s.service().claimRequest(user,{orderId:snapshot.orderId});assert.match(r.challengeId,/^[a-f0-9-]{36}$/);assert.deepEqual(s.getSent().to,['purchase@example.test']);assert.match(s.getCode(),/^\d{8}$/);assert.equal(JSON.stringify(r).includes('purchase@example.test'),false);assert.equal(JSON.stringify(s.rows.purchase_claims).includes(s.getCode()),false)});
test('missing payment email requires support, no mail',async()=>{const s=setup({email:null});await assert.rejects(s.service().claimRequest(user,{orderId:snapshot.orderId}),e=>e.code==='purchase_support_required');assert.equal(s.getSent(),undefined)});
test('refunded purchase cannot get ownership code',async()=>{const s=setup({status:'refunded'});await assert.rejects(s.service().claimRequest(user,{orderId:snapshot.orderId}),e=>e.code==='purchase_not_available');assert.equal(s.getSent(),undefined)});
test('already owned purchase cannot be claimed by another account',async()=>{const s=setup({owner:'other'});await assert.rejects(s.service().claimRequest(user,{orderId:snapshot.orderId}),e=>e.code==='purchase_support_required');assert.equal(s.getSent(),undefined)});
test('shared global mail cap applies to purchase codes',async()=>{const s=setup({mailBudget:false});await assert.rejects(s.service().claimRequest(user,{orderId:snapshot.orderId}),e=>e.code==='rate_limited');assert.equal(s.getSent(),undefined)});
test('claim completion rejects foreign session before granting',async()=>{const s=setup({claimSession:'other'});const r=await s.service().claimRequest(user,{orderId:snapshot.orderId});await assert.rejects(s.service().claimVerify(user,{challengeId:r.challengeId,code:s.getCode()}),e=>e.code==='invalid_code');assert.equal(s.calls.some(c=>c.name==='commerce_finish_claim'),false)});
test('claim completion rechecks provider before atomic grant',async()=>{const s=setup();const r=await s.service().claimRequest(user,{orderId:snapshot.orderId});const result=await s.service().claimVerify(user,{challengeId:r.challengeId,code:s.getCode()});assert.equal(result.ok,true);assert.equal(s.calls.filter(c=>c.name==='commerce_sync_order').length,2);assert.equal(s.calls.findLast(c=>c.name==='commerce_finish_claim').args.p_session,user.sessionId)});
test('cross-user download cannot sign any files',async()=>{const s=setup({owner:'other'});await assert.rejects(s.service().download(user,{orderId:order.id,product:'vocal'}),e=>e.code==='purchase_not_available');assert.equal(s.signs(),0)});
test('refund revalidation prevents signing a previously owned product',async()=>{const s=setup({owner:user.id,status:'refunded'});await assert.rejects(s.service().download(user,{orderId:order.id,product:'vocal'}),e=>e.code==='purchase_not_available');assert.equal(s.signs(),0)});
test('own current purchase gets existing signed releases',async()=>{const s=setup({owner:user.id});const r=await s.service().download(user,{orderId:order.id,product:'vocal'});assert.equal(r.expiresIn,600);assert.equal(r.downloads.length,2);assert.equal(s.signs(),2);assert.equal(r.downloads[0].version,'1.0.0')});

test('session revoked during Square lookup cannot sign files',async()=>{const s=setup({owner:user.id});s.deps.getVerifiedPurchase=async()=>{s.revoke();return snapshot};await assert.rejects(s.service().download(user,{orderId:order.id,product:'vocal'}),e=>e.code==='authentication_required');assert.equal(s.signs(),0)});
