import test from 'node:test';import assert from 'node:assert/strict';import {withAudioAccount} from '../functions/_shared/audio-account.mjs';
const request=(token)=>new Request('https://test',{method:'POST',headers:{origin:'https://zasumaster.com',...(token?{'x-zasu-account-connection':token}:{})},body:JSON.stringify({action:'create_job'})});
test('anonymous request and response remain unchanged',async()=>{const r=new Response('guest',{status:201});const wrapped=withAudioAccount({name:'zasu-mix-api',legacy:async()=>r,authenticate:()=>{throw Error('unexpected')}});assert.equal(await wrapped(request()),r);});
test('invalid scoped connection fails before native job creation',async()=>{let calls=0;const wrapped=withAudioAccount({name:'zasu-mix-api',legacy:async()=>{calls++},authenticate:async()=>null});assert.equal((await wrapped(request('bad'))).status,401);assert.equal(calls,0);});
test('successful creation binds only exact server-returned job',async()=>{let args;const wrapped=withAudioAccount({name:'zasu-mix-api',legacy:async()=>Response.json({job_id:'new',access_token:'a'.repeat(64)}),authenticate:async()=>({id:'user',sessionId:'session'}),bind:async a=>{args=a;return true}});const r=await wrapped(request('zaa_'+'b'.repeat(64)));assert.equal((await r.json()).account_linked,true);assert.equal(args.resource,'new');assert.equal(args.user.id,'user');});
test('post-create binding failure preserves guest success and reports incomplete linkage',async()=>{const wrapped=withAudioAccount({name:'zasu-mix-api',legacy:async()=>Response.json({job_id:'new'}),authenticate:async()=>({id:'user'}),bind:async()=>{throw Error('database')}});const r=await wrapped(request('zaa_'+'b'.repeat(64)));assert.equal(r.status,200);assert.equal((await r.json()).account_linked,false);});
test('reused MASTER upload is never re-assigned by wrapper',async()=>{let calls=0;const wrapped=withAudioAccount({name:'create-master-from-zasu-mix',legacy:async()=>Response.json({reused:true,upload_id:'old'}),authenticate:async()=>({id:'user'}),bind:async()=>{calls++;return true}});assert.equal((await(await wrapped(request('zaa_'+'b'.repeat(64)))).json()).account_linked,false);assert.equal(calls,0);});
test('actual CONVERT create_upload action binds new job',async()=>{let count=0;const wrapped=withAudioAccount({name:'convert-api',legacy:async()=>Response.json({job_id:'new'}),authenticate:async()=>({id:'user'}),bind:async()=>{count++;return true}});const req=new Request('https://test',{method:'POST',headers:{origin:'https://zasumaster.com','x-zasu-account-connection':'zaa_'+'b'.repeat(64)},body:JSON.stringify({action:'create_upload'})});assert.equal((await(await wrapped(req)).json()).account_linked,true);assert.equal(count,1)});
test('connection preflight preserves existing staging authorization headers',async()=>{const wrapped=withAudioAccount({name:'convert-api',legacy:async()=>new Response(null,{status:204,headers:{'Access-Control-Allow-Headers':'authorization, content-type, x-phase0-key'}})});const req=new Request('https://test',{method:'OPTIONS',headers:{origin:'https://zasumaster.com','access-control-request-headers':'x-zasu-account-connection,x-phase0-key'}});const r=await wrapped(req);assert.match(r.headers.get('Access-Control-Allow-Headers'),/x-phase0-key/);assert.match(r.headers.get('Access-Control-Allow-Headers'),/x-zasu-account-connection/)});
