import {test} from 'node:test';import assert from 'node:assert/strict';
let createSquare;try{({createSquare}=await import('../functions/zasu-account/square.mjs'))}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e}
const pid='Payment12345678901234567890',oid='Order12345678901234567890',receipt='https://squareup.com/r/Receipt12345678901234567890';
test('Square adapter exists',()=>assert.equal(typeof createSquare,'function'));
test('foreign receipt host cannot cause a fetch',async()=>{let calls=0;const s=createSquare({token:'fixture',fetchImpl:async()=>{calls++;throw Error('unexpected')}});await assert.rejects(s.resolveOrder({receiptUrl:'https://evil.test/r/1234567890123456'}));assert.equal(calls,0)});
test('reference cannot choose arbitrary API path',async()=>{let calls=0;const s=createSquare({token:'fixture',fetchImpl:async()=>{calls++;throw Error('unexpected')}});await assert.rejects(s.resolveOrder({paymentId:'../../secrets'}));assert.equal(calls,0)});
test('receipt requires merchant product and exactly one full payment link',async()=>{const calls=[];const s=createSquare({token:'fixture',fetchImpl:async(url,options)=>{calls.push({url,options});return url===receipt?new Response(`ZASU WORKS ZASU DAW <a href="https://squareup.com/receipts/pt/${pid}">receipt</a>`,{headers:{'content-type':'text/html'}}):Response.json({payment:{id:pid,order_id:oid}})}});assert.equal(await s.resolveOrder({receiptUrl:receipt}),oid);assert.equal(calls[0].options.redirect,'error');assert.equal(calls[1].url,`https://connect.squareup.com/v2/payments/${pid}`)});
test('receipt without full payment link never guesses short receipt ID',async()=>{const s=createSquare({token:'fixture',fetchImpl:async()=>new Response('ZASU WORKS ZASU LOUD receipt 1234',{headers:{'content-type':'text/html'}})});await assert.rejects(s.resolveOrder({receiptUrl:receipt}),e=>e.code==='receipt_lookup_incomplete')});
test('private inventory reports missing provider configuration without exposing credentials',async()=>{const s=createSquare({fetchImpl:async()=>{throw Error('unexpected')}});assert.deepEqual(await s.inventory(),{squareConfigured:false,subscriptionsReadable:false,reason:'not_configured',subscriptions:[]})});
test('refund configuration preserves existing events and changes only event types',async()=>{const endpoint='https://siwmzradvrtetotakkbi.supabase.co/functions/v1/square-payment-webhook',calls=[];const sub={id:'wbhk_fixture1234567890',enabled:true,notification_url:endpoint,event_types:['payment.created','payment.updated','other.event']};const s=createSquare({token:'fixture',fetchImpl:async(url,options)=>{calls.push({url,options});return Response.json({subscriptions:[sub],subscription:{...sub,event_types:[...sub.event_types,'refund.created','refund.updated']}})}});assert.deepEqual(await s.configureRefunds(endpoint),{configured:true,changed:true});assert.equal(calls[1].options.method,'PUT');assert.deepEqual(JSON.parse(calls[1].options.body),{subscription:{event_types:[...sub.event_types,'refund.created','refund.updated']}})});
test('refund configuration is idempotent and refuses absent or ambiguous subscription',async()=>{const endpoint='https://siwmzradvrtetotakkbi.supabase.co/functions/v1/square-payment-webhook';for(const count of [0,1,2]){let writes=0;const sub={id:'wbhk_fixture1234567890',enabled:true,notification_url:endpoint,event_types:['payment.created','refund.created','refund.updated']};const s=createSquare({token:'fixture',fetchImpl:async(url,o)=>{if(o.method)writes++;return Response.json({subscriptions:Array(count).fill(sub)})}});if(count===1)assert.deepEqual(await s.configureRefunds(endpoint),{configured:true,changed:false});else await assert.rejects(s.configureRefunds(endpoint));assert.equal(writes,0)}});
test('refund configuration refuses foreign endpoint before any request',async()=>{let calls=0;const s=createSquare({token:'fixture',fetchImpl:async()=>calls++});await assert.rejects(s.configureRefunds('https://evil.test'));assert.equal(calls,0)});
