import {test} from 'node:test';import assert from 'node:assert/strict';
import {createServiceRouter} from '../functions/zasu-account/service.mjs';
let createAccountWebhook,createEventConsumer;try{({createAccountWebhook,createEventConsumer}=await import('../functions/zasu-account/webhook.mjs'))}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e}
const pid='Payment12345678901234567890';
const event={event_id:'event-123',type:'payment.updated',data:{object:{payment:{id:pid,status:'COMPLETED'}}}};
const request=()=>new Request('https://example.test/hook',{method:'POST',headers:{'x-square-hmacsha256-signature':'fixture'},body:JSON.stringify(event)});
test('webhook modules exist',()=>{assert.equal(typeof createAccountWebhook,'function');assert.equal(typeof createEventConsumer,'function')});
test('invalid signature cannot call either commerce or legacy fulfillment',async()=>{let calls=0;const handler=createAccountWebhook({verifySignature:async()=>false,legacyHandler:async()=>{calls++},processEvent:async()=>{calls++}});assert.equal((await handler(request())).status,403);assert.equal(calls,0)});
test('account failure still runs existing guest fulfillment and returns retry',async()=>{let legacy=0;const h=createAccountWebhook({verifySignature:async()=>true,legacyHandler:async()=>{legacy++;return Response.json({guest:'sent'})},processEvent:async()=>{throw Error('account_database_outage')}});assert.equal((await h(request())).status,503);assert.equal(legacy,1)});
test('legacy duplicate response still retries unfinished account consumer',async()=>{let called=0;const h=createAccountWebhook({verifySignature:async()=>true,legacyHandler:async()=>Response.json({duplicate:true}),processEvent:async()=>{called++}});assert.equal((await h(request())).status,200);assert.equal(called,1)});
test('provider fetch failure releases task as failed for replay',async()=>{const calls=[];const rpc=async(n,a)=>{calls.push({n,a});return n==='commerce_lease_event'?{token:'lease',paymentId:pid}:true};const c=createEventConsumer({rpc,square:{getPayment:async()=>{throw Error('outage')}},commerce:{refresh:async()=>{}}});await assert.rejects(c(event),/outage/);assert.deepEqual(calls.at(-1),{n:'commerce_finish_event',a:{p_event:'event-123',p_token:'lease',p_success:false}})});
test('duplicate completed task makes no provider call',async()=>{let calls=0;const c=createEventConsumer({rpc:async()=>({done:true}),square:{getPayment:async()=>{calls++;throw Error('unexpected')}},commerce:{}});await c(event);assert.equal(calls,0)});
test('refund notification fetches current payment and order instead of trusting payload',async()=>{const calls=[];const c=createEventConsumer({rpc:async(n,a)=>{calls.push({n,a});return n==='commerce_lease_event'?{token:'lease',paymentId:pid}:true},square:{getPayment:async id=>{assert.equal(id,pid);return {id:pid,order_id:'Order12345678901234567890'}}},commerce:{refresh:async id=>calls.push({order:id})}});await c({event_id:'refund-event',type:'refund.updated',data:{object:{refund:{payment_id:pid,status:'COMPLETED'}}}});assert.equal(calls[1].order,'Order12345678901234567890');assert.equal(calls.at(-1).a.p_success,true)});

test('large signed event is compacted before forwarding to 4KB internal router',async()=>{let tasks=0,legacy=0;const inner=createServiceRouter({key:'fixture-key',accountHandler:async()=>new Response('',{status:403}),authorizeRecovery:async()=>false,processEvent:async e=>{assert.equal(e.data.object.payment.id,pid);tasks++}});const outer=createAccountWebhook({verifySignature:async()=>true,legacyHandler:async()=>{legacy++;return Response.json({ok:true})},processEvent:async e=>{const r=await inner(new Request('https://example.test',{method:'POST',headers:{authorization:'Bearer fixture-key'},body:JSON.stringify({action:'commerce_event',event:e})}));assert.equal(r.status,200)}});const r=await outer(new Request('https://example.test/hook',{method:'POST',body:JSON.stringify({...event,padding:'x'.repeat(10000)})}));assert.equal(r.status,200);assert.equal(tasks,1);assert.equal(legacy,1)});
