import {SUPABASE_URL,PUBLISHABLE_KEY} from './config.mjs';
const ENDPOINT=SUPABASE_URL+'/functions/v1/zasu-account',STORE='zasu.account.session.v1';
const $=id=>document.getElementById(id);
let session=null,account=null,purpose='login',challenge=null,email='',closeChallenge=null,resendAt=0,refreshing=null,purchaseChallenge=null,purchaseResendAt=0;
try{session=JSON.parse(sessionStorage.getItem(STORE)||'null')}catch{sessionStorage.removeItem(STORE)}
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('zasu-account'):null;
channel?.addEventListener('message',e=>{if(e.data==='global-logout'){clearSession();show('auth');notify('すべての端末からログアウトしました。')}});
function persist(s){session=s;sessionStorage.setItem(STORE,JSON.stringify(s));}
function clearSession(){session=null;account=null;sessionStorage.removeItem(STORE);$('profile-form').reset();$('close-form').reset();$('close-form').hidden=true;$('close-consent').checked=false;closeChallenge=null;for(const id of ['user-name','user-email','settings-email','settings-id','settings-created'])$(id).textContent='';$('display-name').value='';$('purchase-list').replaceChildren();$('purchase-reference-form').reset();$('purchase-code-form').reset();$('purchase-code-form').hidden=true;$('commerce-nav').hidden=true;purchaseChallenge=null;purchaseResendAt=0;}
function notify(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);$('notice').hidden=!message;}
function show(view){for(const id of ['auth','dashboard','settings','purchases','loading'])$(id).hidden=id!==view;$('account-nav').hidden=!session;document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});}
function authMode(mode){purpose=mode;challenge=null;email='';$('code-form').hidden=true;$('email-form').hidden=false;$('code').value='';$('consent-row').hidden=mode!=='signup';$('consent').required=mode==='signup';$('auth-title').textContent=mode==='signup'?'創作の道具を、ひとつに。':'おかえりなさい。';$('signup-tab').setAttribute('aria-pressed',String(mode==='signup'));$('login-tab').setAttribute('aria-pressed',String(mode==='login'));notify('');}
const messages={purchase_not_available:'この購入は確認中・返金済み、または利用できない状態です。サポートへお問い合わせください。',purchase_not_verified:'購入を確認できませんでした。領収書・取引IDをご確認ください。',purchase_support_required:'この購入はサポートでの確認が必要です。購入時の領収書を添えてお問い合わせください。',receipt_lookup_incomplete:'領収書URLから決済IDを確認できませんでした。注文ID・決済IDでお試しいただくか、サポートへお問い合わせください。',invalid_purchase_reference:'Squareの領収書URL、注文ID、決済IDのいずれかを入力してください。',invalid_code:'コードが正しくないか、有効期限が切れています。新しいコードを送信してください。',rate_limited:'送信・確認の回数が上限に達しました。時間をおいてお試しください。',consent_required:'プライバシーポリシーへの同意が必要です。',invalid_profile:'表示名は80文字以内で入力してください。',authentication_required:'ログインの有効期限が切れました。もう一度ログインしてください。',temporarily_unavailable:'ただいま接続できません。時間をおいてお試しください。'};
async function refresh(){if(!session)throw Error('authentication_required');if(refreshing)return refreshing;refreshing=(async()=>{const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token}),signal:AbortSignal.timeout(15000)});if(!r.ok){if(r.status>=500)throw Error('temporarily_unavailable');clearSession();show('auth');throw Error('authentication_required')}const s=await r.json();if(!s.access_token||!s.refresh_token)throw Error('temporarily_unavailable');persist({access_token:s.access_token,refresh_token:s.refresh_token,expires_at:s.expires_at,user:{id:s.user.id,email:s.user.email}});})().finally(()=>refreshing=null);return refreshing}
async function api(body,authenticated=false){if(authenticated){if(!session)throw Error('authentication_required');if(!Number.isFinite(session.expires_at)||session.expires_at<Date.now()/1000+60)await refresh()}
 const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json',...(authenticated?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});let data;try{data=await r.json()}catch{throw Error('temporarily_unavailable')}
 if(r.status===401){clearSession();show('auth');authMode('login')}
 if(!r.ok)throw Error(data.error||'temporarily_unavailable');return data;
}
async function busy(container,fn){const buttons=[...container.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);notify('');try{await fn()}catch(e){notify(messages[e.message]||messages.temporarily_unavailable,true)}finally{buttons.forEach(b=>b.disabled=false);updateResend()}}
function updateResend(){const seconds=Math.max(0,Math.ceil((resendAt-Date.now())/1000));$('resend').disabled=seconds>0;$('resend').textContent=seconds>0?`再送まで ${seconds} 秒`:'再送する';}
async function requestCode(){const data=await api({action:'request',email,purpose,consent:purpose==='signup'&&$('consent').checked});challenge=data.challengeId;resendAt=Date.now()+60000;$('email-form').hidden=true;$('code-form').hidden=false;$('code-destination').textContent=email+' に確認コードを送信できる場合はお送りします。';$('code').value='';updateResend();$('code').focus();}
function renderAccount(data){account=data;$('commerce-nav').hidden=!data.purchasesIntegrated;$('purchase-summary').hidden=!data.purchasesIntegrated;$('purchase-placeholder').hidden=!!data.purchasesIntegrated;$('purchase-pill').textContent=data.purchasesIntegrated?'購入管理':'準備中';const name=data.profile.display_name; $('user-name').textContent=name||'クリエイター';$('user-email').textContent=data.user.email;$('settings-email').textContent=data.user.email;$('settings-id').textContent=data.user.id;$('settings-created').textContent=new Date(data.profile.created_at).toLocaleDateString('ja-JP');$('display-name').value=name;$('locale').value=data.profile.locale;}
$('login-tab').addEventListener('click',()=>authMode('login'));$('signup-tab').addEventListener('click',()=>authMode('signup'));
$('email-form').addEventListener('submit',e=>{e.preventDefault();email=$('email').value.trim().toLowerCase();busy($('email-form'),requestCode)});
$('code-form').addEventListener('submit',e=>{e.preventDefault();busy($('code-form'),async()=>{const data=await api({action:'verify',challengeId:challenge,code:$('code').value.trim()});persist(data.session);$('code').value='';$('email').value='';challenge=null;renderAccount(await api({action:'me'},true));show('dashboard');notify('メール認証が完了しました。');$('dashboard').querySelector('h1').focus();})});
$('resend').addEventListener('click',()=>busy($('code-form'),requestCode));$('change-email').addEventListener('click',()=>{authMode(purpose);$('email').focus()});
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>{notify('');show(b.dataset.view);if(b.dataset.view==='purchases')busy($('purchases'),loadPurchases)});
$('profile-form').addEventListener('submit',e=>{e.preventDefault();busy($('profile-form'),async()=>{const data=await api({action:'update',display_name:$('display-name').value,locale:$('locale').value},true);renderAccount({...account,profile:data.profile});notify('変更を保存しました。');})});
for(const scope of ['local','global'])$('logout-'+scope).addEventListener('click',()=>busy($('settings'),async()=>{await api({action:'logout',scope},true);clearSession();authMode('login');show('auth');if(scope==='global')channel?.postMessage('global-logout');notify('ログアウトしました。');}));
$('request-close').addEventListener('click',()=>{if(!$('close-consent').checked){notify('停止の説明を確認して、チェックしてください。',true);return}busy($('settings'),async()=>{const data=await api({action:'request',email:account.user.email,purpose:'close'},true);closeChallenge=data.challengeId;$('close-form').hidden=false;$('close-code').value='';$('close-code').focus();notify('停止用の確認コードを送信できる場合はお送りします。');})});
$('close-form').addEventListener('submit',e=>{e.preventDefault();busy($('close-form'),async()=>{await api({action:'close',challengeId:closeChallenge,code:$('close-code').value.trim()},true);clearSession();channel?.postMessage('global-logout');authMode('login');show('auth');notify('アカウントを停止しました。');})});
window.addEventListener('pageshow',e=>{if(e.persisted&&session)loadAccount()});
async function loadAccount(){show('loading');try{renderAccount(await api({action:'me'},true));show('dashboard')}catch(e){if(!session)show('auth');else show('loading');notify(messages[e.message]||messages.temporarily_unavailable,true)}}
setInterval(updateResend,1000);
if(session)loadAccount();else{authMode('login');show('auth');}

const productNames={vocal:'VOCAL',loud:'LOUD',daw:'DAW'};
const purchaseStates={paid:'利用可能',pending:'決済確認中',refund_pending:'返金処理中',refunded:'返金済み',review:'サポート確認が必要',void:'取り消し済み'};
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
async function loadPurchases(){
 const data=await api({action:'purchases'},true);$('purchase-list').replaceChildren();
 if(!data.purchases.length){$('purchase-list').append(element('p','購入はまだ追加されていません。上のフォームから、購入確認後に追加できます。','fine'));return;}
 for(const p of data.purchases){
  const card=element('article',undefined,'purchase-card');card.append(element('h3',p.title),element('p',`${new Date(p.purchasedAt).toLocaleDateString('ja-JP')} ・ ¥${p.amount.toLocaleString('ja-JP')} ・ 購入版 ${p.purchasedVersion}`,'fine'),element('p',purchaseStates[p.status]||'確認中','pill'));
  for(const product of p.products){const section=element('div',undefined,'owned-product');section.append(element('p',`ZASU ${productNames[product.key]||product.key} — 配布版 ${product.version||'確認中'}`));
   if(p.status==='paid'){const button=element('button',`${productNames[product.key]}をダウンロード`,'secondary');button.type='button';const links=element('div',undefined,'signed-downloads');button.addEventListener('click',()=>busy(section,async()=>{links.replaceChildren();const data=await api({action:'download',orderId:p.id,product:product.key},true);for(const file of data.downloads){const url=new URL(file.url);if(url.origin!==new URL(SUPABASE_URL).origin||!url.pathname.startsWith('/storage/v1/object/sign/'))throw Error('temporarily_unavailable');const a=element('a',`${file.os==='mac'?'macOS':'Windows'} — ${file.version}`);a.href=url.href;a.rel='noopener';a.target='_blank';links.append(a);}links.append(element('p','リンクの有効期限は10分です。期限切れの場合は再取得してください。','fine'));setTimeout(()=>links.replaceChildren(),600000);}));section.append(button,links);}card.append(section);
  }$('purchase-list').append(card);
 }
}
$('purchase-reference-form').addEventListener('submit',e=>{e.preventDefault();if(purchaseResendAt>Date.now()){notify('再送まで少しお待ちください。',true);return}busy($('purchase-reference-form'),async()=>{const reference=$('purchase-reference').value.trim();const data=await api({action:'claim_request',[$('purchase-reference-type').value]:reference},true);purchaseChallenge=data.challengeId;purchaseResendAt=Date.now()+60000;$('purchase-code-form').hidden=false;$('purchase-code').value='';$('purchase-code').focus();notify('購入時に記録されたメールアドレスへ確認コードを送りました。');})});
$('purchase-code-form').addEventListener('submit',e=>{e.preventDefault();busy($('purchase-code-form'),async()=>{await api({action:'claim_verify',challengeId:purchaseChallenge,code:$('purchase-code').value.trim()},true);purchaseChallenge=null;$('purchase-code-form').reset();$('purchase-code-form').hidden=true;await loadPurchases();notify('購入をアカウントに追加しました。');})});
$('purchase-reload').addEventListener('click',()=>busy($('purchases'),loadPurchases));
