// Task-scoped release transfer only. No purchase, payment or customer lookup.
// A random capability is generated by Work per execution; only its hash is deployed.
export function transferHandler({ tokenHash, expiresAt, files, storage, digest }) {
  const reply = (status, data) => new Response(JSON.stringify(data), {
    status, headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' }
  });
  return async req => {
    if (Date.now() >= expiresAt) return reply(410, { error: 'expired' });
    if (req.headers.has('Origin')) return reply(403, { error: 'browser_not_allowed' });
    const token = req.headers.get('Authorization')?.replace(/^Bearer /, '') || '';
    if (!/^[a-f0-9]{64}$/.test(token) || await digest(new TextEncoder().encode(token)) !== tokenHash)
      return reply(401, { error: 'unauthorized' });
    const url = new URL(req.url), path = url.searchParams.get('path');
    const file = files.find(f => f.path === path);
    if (!file) return reply(403, { error: 'path_not_allowed' });
    try {
      if (req.method === 'GET') {
        const { data, error } = await storage.createSignedUrl(path, 600, { download: path.split('/').at(-1) });
        if (error || !data?.signedUrl) throw new Error();
        return reply(200, { url: data.signedUrl });
      }
      if (req.method !== 'PUT' || !file.upload) return reply(405, { error: 'read_only' });
      if (Number(req.headers.get('Content-Length')) !== file.size || file.size > 52428800)
        return reply(413, { error: 'size_mismatch' });
      const reader = req.body?.getReader();
      if (!reader) return reply(400, { error: 'empty_body' });
      const chunks = []; let length = 0;
      while (true) {
        const { done, value } = await reader.read(); if (done) break;
        length += value.length;
        if (length > file.size) { await reader.cancel(); return reply(413, { error: 'size_mismatch' }); }
        chunks.push(value);
      }
      const bytes = new Uint8Array(length); let offset = 0;
      for (const c of chunks) { bytes.set(c, offset); offset += c.length; }
      if (length !== file.size || await digest(bytes) !== file.sha256)
        return reply(422, { error: 'hash_mismatch' });
      // Never overwrite an existing release or rollback file.
      const { error } = await storage.upload(path, bytes, { upsert: false, contentType: 'application/octet-stream' });
      if (error) return reply(409, { error: 'not_created' });
      return reply(201, { sha256: file.sha256, size: length });
    } catch { return reply(503, { error: 'storage_unavailable' }); }
  };
}
